name: GitHub to Bitbucket Migration

on:
  workflow_dispatch:  # Manual trigger
    inputs:
        BITBUCKET_USER:
          description: 'Bitbucket Username (used for SSH URLs)'
          required: true
        GITHUB_USER:
          description: 'GitHub Username (used for SSH URLs)'
          required: true

jobs:
  migrate-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migration script
        run: |
          python main.py
          
        env:
          PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_USER: ${{ inputs.GITHUB_USER }}
          BITBUCKET_USER: ${{ inputs.BITBUCKET_USER }}
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKETUSERNAME }}
          BITBUCKET_WORKSPACE: ${{ secrets.BITBUCKET_WORKSPACE }}
          
          
